services:
  - type: web
    name: nine-dart-nation-api
    env: node
    rootDirectory: server
    buildCommand: |
      # Install server deps
      npm ci
      # Build frontend bundle(s). We try root first, then app/ if present.
      if [ -f ../package.json ]; then
        cd .. && npm ci && npm run build || true
        cd -
      fi
      if [ -d ../app ]; then
        cd ../app && npm ci && npm run build || true
        cd -
      fi
    startCommand: npm start
    healthCheckPath: /readyz
    autoDeploy: true
    plan: free
    envVars:
      - key: LOG_LEVEL
        value: info
      # Add these in the Render dashboard or here if you prefer
      # - key: SMTP_HOST
      #   sync: false
      # - key: SMTP_PORT
      #   sync: false
      # - key: SMTP_USER
      #   sync: false
      # - key: SMTP_PASS
      #   sync: false
      # - key: SMTP_FROM
      #   sync: false
      # - key: STRIPE_SECRET_KEY
      #   sync: false
      # - key: STRIPE_PRICE_ID_USERNAME_CHANGE
      #   sync: false
      # - key: STRIPE_PRICE_ID_SUBSCRIPTION
      #   sync: false
      # - key: STRIPE_WEBHOOK_SECRET
      #   sync: false
