services:
  - type: web
    name: nine-dart-nation-api
    env: node
    buildCommand: |
      # Install all dependencies
      npm ci
      # Install server-specific dependencies
      cd server && npm ci && cd ..
      # Build frontend
      npm run build
    startCommand: cd server && npm start
    healthCheckPath: /readyz
    autoDeploy: true
    plan: free
    envVars:
      - key: LOG_LEVEL
        value: info
      - key: REDIS_FORCE_TLS
        value: 1
      - key: REDIS_TLS_REJECT_UNAUTHORIZED
        value: false
      - key: UPSTASH_REDIS_REST_URL
        value: https://settling-lamb-23630.upstash.io
      - key: UPSTASH_REDIS_REST_TOKEN
        value: AVxOAAIncDIzMzk5NGM3YTZmZjg0Mzg4OTJhNWNjMWYyN2ZiOTNhOHAyMjM2MzA
      # Add these in the Render dashboard or here if you prefer
      # - key: SMTP_HOST
      #   sync: false
      # - key: SMTP_PORT
      #   sync: false
      # - key: SMTP_USER
      #   sync: false
      # - key: SMTP_PASS
      #   sync: false
      # - key: SMTP_FROM
      #   sync: false
      # - key: STRIPE_SECRET_KEY
      #   sync: false
      # - key: STRIPE_PRICE_ID_USERNAME_CHANGE
      #   sync: false
      # - key: STRIPE_PRICE_ID_SUBSCRIPTION
      #   sync: false
      # - key: STRIPE_WEBHOOK_SECRET
      #   sync: false
