[build]
  # Build the Vite app from the app/ directory
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  # VITE_WS_URL should be set in Netlify site settings, not here
  # VITE_WS_URL = "wss://your-render-service.onrender.com"

# Security and caching headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Permissions-Policy = "camera=(self), microphone=(self), geolocation=(), payment=(), interest-cohort=()"
    # HTML and non-hashed content should not be aggressively cached
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  # Vite emits hashed asset filenames under /assets; safe to cache long-term
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"